### ISSUE TITLE
Not grabbing markdownlintrc config file

### ISSUE THREAD

**Issue by brandonh-msft** [DavidAnson/markdownlint-cli2-action#1]
I have a `.markdownlintrc` file in the root of my repo with the following content:
```jsonc
{
    // From https://github.com/DavidAnson/markdownlint/blob/main/style/relaxed.json
    "comment": "Relaxed rules",

    "default": true,
    "whitespace": false,
    "line_length": false,
    "ul-start-left": false,
    "ul-indent": false,
    "no-inline-html": false,
    "no-bare-urls": false,
    "fenced-code-language": false,
    "first-line-h1": false
  }
```

Yet running this action in my workflow yields failures that shouldn't be happening based on this config:
~~~
Error: doc/write-raw-data-to-storage/README.md:3:81 MD013/line-length Line length [Expected: 80; Actual: 207]
Error: doc/write-raw-data-to-storage/README.md:5:81 MD013/line-length Line length [Expected: 80; Actual: 91]
Error: doc/write-raw-data-to-storage/README.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 239]
...
~~~

I see no docs on how to specify a config file or that `.markdownlintrc` is not a supported config type and `markdownlint-cli` docs say:
> The CLI argument --config is not required. If it is not provided, markdownlint-cli looks for the file .markdownlint.json/.markdownlint.yaml/.markdownlint.yml in current folder, or for the file .markdownlintrc in the current or all parent folders.

**Comment by brandonh-msft** [comment]
I did some troubleshooting and renamed my `.markdownlintrc` to `.markdownlint.jsonc` and the action picked up the file as expected. Looks like RC filetype just isn't supported (and should be)

**Comment by DavidAnson** [comment]
`markdownlintrc` is not one of the supported formats for CLI2, all of which are documented here: https://github.com/DavidAnson/markdownlint-cli2

It is supported by CLI1 as an artifact of the`rc` library it uses for argument parsing. It offers nothing beyond what other supported formats do, and I do not intend to include it because it has some strange expectations. The next release of the VS Code extension will remove support for that file type for these reasons.

**Comment by brandonh-msft** [comment]
Good to know - thanks!
